sources:
  - name: clober-v1
    handler:
      graphql:
        endpoint: '{context.url:https://api.goldsky.com/api/public/project_clsljw95chutg01w45cio46j0/subgraphs/core-v1-subgraph/1.0.0/gn}'

documents:
  - ./apis/**/*.graphql
  - ./__tests__/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
